<?php
/***** SPICE-HEADER-SPACEHOLDER *****/

namespace SpiceCRM\modules\EmployeeAbsences;

use DateTime;
use SpiceCRM\includes\SpiceBeans\BeanFactory;
use SpiceCRM\includes\authentication\AuthenticationController;
use SpiceCRM\includes\SpiceBeans\SpiceBean;
use SpiceCRM\includes\SpiceDictionary\database\DBManagerFactory;
use SpiceCRM\includes\SugarObjects\LanguageManager;
use SpiceCRM\includes\SugarObjects\SpiceConfig;
use SpiceCRM\includes\TimeDate;
use SpiceCRM\includes\utils\SpiceUtils;

class EmployeeAbsence extends SpiceBean
{

    public function retrieve($id = -1, $encode = false, $deleted = true, $relationships = true)
    {
        $bean = parent::retrieve($id, $encode, $deleted, $relationships); // TODO: Change the autogenerated stub
        $bean->getRepresentationWarning($bean);
    }

    public function get_summary_text()
    {
        $currentUser = AuthenticationController::getInstance()->getCurrentUser();

        $language = $currentUser->getPreference('language');
        if ( empty( $language )) $language = LanguageManager::getDefaultLanguage();
        $app_list_strings = SpiceUtils::returnAppListStringsLanguage( $language );

        $dateFormat = $currentUser->getPreference('datef');
        # if ( empty( $dateFormat )) $dateFormat = SpiceConfig::getInstance()->config['default_date_format'];
        if ( empty( $dateFormat )) $dateFormat = SpiceConfig::getInstance()->config['default_preferences']['datef'];
        $start = ( new \DateTime( $this->date_start ))->format( $dateFormat );

        return $app_list_strings['absencetypes'][$this->type].', '.$start;
    }

    public function getSubstituteIDs()
    {

        if(isset($_SESSION['user_substituting_for'])){
            return $_SESSION['user_substituting_for'];
        } else {
            $current_user = AuthenticationController::getInstance()->getCurrentUser();
            $db = DBManagerFactory::getInstance();
            $timeDate = TimeDate::getInstance();
            $userIDs = [];
            $today = new DateTime();
            $today = $today->format($timeDate->get_date_format());
            $substituteids = $db->query("SELECT distinct assigned_user_id FROM employeeabsences WHERE representative_id='{$current_user->parent_id}' AND date_start <= '$today' AND date_end >= '$today' AND deleted = 0");
            while ($substitute = $db->fetchByAssoc($substituteids)) {
                $userIDs[] = $substitute['assigned_user_id'];
            }

            $_SESSION['user_substituting_for'] = $userIDs;

            return $userIDs;
        }
    }

    /**
     * @deprecated since 2023.03.001
     * @return array
     * @throws \Exception
     */
    public function getSubstituteOrgUnitIDs()
    {
        return $this->getSubstituteEmployeeOrgUnitIDs();

//        $current_user = AuthenticationController::getInstance()->getCurrentUser();
//        $db = DBManagerFactory::getInstance();
//        $timeDate = TimeDate::getInstance();
//        $userIDs = [];
//        $today = new DateTime();
//        $today = $today->format($timeDate->get_date_format());
//        $substituteids = $db->query("SELECT distinct orgunit_id FROM users, userabsences WHERE users.id = userabsences.assigned_user_id AND representative_id='{$current_user->id}' AND date_start <= '$today' AND date_end >= '$today' AND userabsences.deleted = 0");
//        while ($substitute = $db->fetchByAssoc($substituteids)) {
//            $userIDs[] = $substitute['orgunit_id'];
//        }
//        return $userIDs;
    }

    /**
     * get the orgunits allocate to the employee object of the substitute
     * @return array
     * @throws \Exception
     */
    public function getSubstituteEmployeeOrgUnitIDs()
    {
        $current_user = AuthenticationController::getInstance()->getCurrentUser();
        $db = DBManagerFactory::getInstance();
        $timeDate = TimeDate::getInstance();
        $orgUnitIDs = [];
        $today = new DateTime();
        $today = $today->format($timeDate->get_date_format());
        $substituteids = $db->query("SELECT distinct oe.orgunit_id FROM users, employeeabsences, orgunits_beans oe WHERE users.parent_id = oe.bean_id AND oe.deleted=0 AND users.id = employeeabsences.assigned_user_id AND representative_id='{$current_user->parent_id}' AND date_start <= '$today' AND date_end >= '$today' AND employeeabsences.deleted = 0");
        while ($substitute = $db->fetchByAssoc($substituteids)) {
            $orgUnitIDs[] = $substitute['orgunit_id'];
        }
        return $orgUnitIDs;
    }

    public function getRepresentationWarning(){
        $text = [];
        if(AuthenticationController::getInstance()->getCurrentUser()->parent_id == $this->employee_id){
            $q = "SELECT id FROM employeeabsences WHERE STATUS IN('submitted','approved') AND deleted = 0 AND representative_id = '{$this->employee_id}' ";
            $q.= " AND (
                (date_start <='{$this->date_start}' AND date_end >= '{$this->date_end}')
                OR
                (date_start <='{$this->date_start}' AND date_end >= '{$this->date_start}')
                OR
                (date_start <='{$this->date_end}' AND date_end >= '{$this->date_end}')
                OR
                (date_start >='{$this->date_start}' AND date_end <= '{$this->date_end}')
            )";

            $rows = \SpiceCRM\includes\SpiceDictionary\database\DBManagerFactory::getInstance()->fetchAll($q);
            if(is_array($rows)){
                foreach($rows as $row){
                    $absence = BeanFactory::getBean('EmployeeAbsences', $row['id'], ['relationships' => false]);
                    $snippet = BeanFactory::getBean('TextSnippets', SpiceConfig::getInstance()->config['EmployeeAbsences']['warning_textsnippet_id']);
                    if($snippet){
                        $text[] = $snippet->parse($absence);
                    }
                }
            }

            // allocate value
            $this->warning_message = implode("<br>", $text);

        }
    }
}
