<?php
/***** SPICE-HEADER-SPACEHOLDER *****/

namespace SpiceCRM\modules\ScrumThemes;

use SpiceCRM\data\SugarBean;

class ScrumTheme extends SugarBean {
    public $module_dir = 'ScrumThemes';
    public $object_name = 'ScrumTheme';
    public $table_name = 'scrumthemes';

    public function save($check_notify = false, $fts_index_bean = true)
    {
        $this->has_epics = false;

       return parent::save($check_notify, $fts_index_bean); // TODO: Change the autogenerated stub
    }

    public function retrieve($id = -1, $encode = false, $deleted = true, $relationships = true)
    {
        $bean = parent::retrieve($id, $encode, $deleted, $relationships); // TODO: Change the autogenerated stub

        // set has_epics to true if there are related epics
        if(isset($this->id)) {
            $epics = $bean->get_linked_beans('scrumepics', $this->object_name);
            if (count($epics) > 0) {
                $this->has_epics = true;
            }
        }
        return $bean;
    }
}
