<?php
/***** SPICE-SUGAR-HEADER-SPACEHOLDER *****/
namespace SpiceCRM\modules\Employees;

use SpiceCRM\data\BeanFactory;
use SpiceCRM\includes\SugarObjects\templates\person\Person;

class Employee extends Person {

	public function __construct() {
		parent::__construct();
		$this->emailAddress = BeanFactory::getBean('EmailAddresses');
	}

    public function retrieveViewDetails()
    {
        parent::retrieveViewDetails(); // TODO: Change the autogenerated stub
        // get primary orgunit
        $primaryOrgUnit = $this->getPrimaryOrgUnit();
        if($primaryOrgUnit){
            $this->orgunit_id = $primaryOrgUnit->id;
            $this->orgunit_name = $primaryOrgUnit->name;
        }
    }

    /**
     * return the primary orgunit object for the employee
     * @return false|mixed
     */
    public function getPrimaryOrgUnit(){
        $orgunit = $this->get_linked_beans('orgunitprimary');
        if(count($orgunit) > 0){
            return $orgunit[0];
        }
        return false;
    }

}
