<?php
/***** SPICE-SUGAR-HEADER-SPACEHOLDER *****/
namespace SpiceCRM\modules\Employees;

use SpiceCRM\data\BeanFactory;
use SpiceCRM\includes\SugarObjects\templates\person\Person;

class Employee extends Person {

	public function __construct() {
		parent::__construct();
		$this->emailAddress = BeanFactory::getBean('EmailAddresses');
	}

    public function retrieveViewDetails()
    {
        parent::retrieveViewDetails(); // TODO: Change the autogenerated stub
        // get primary orgunit
        $orgunit = $this->get_linked_beans('orgunitprimary');
        if(count($orgunit) > 0){
            $this->orgunit_id = $orgunit[0]->id;
            $this->orgunit_name = $orgunit[0]->name;
        }
    }

}
